
# Makefile for the fast inverse halftoning algorithm programs
# fastiht1 and fastiht2.  The fastiht2.c does not depend on
# any other files in this directory.
#
# Author: Niranjan Damera-Venkata and Brian L. Evans
# Version: @(#)Makefile	1.17	06/21/98

CC =	gcc
OPTIMIZER = -O3
LINKER = gcc

HFILES = image_io.h inverse_halftone.h matrix_utils.h readWriteImage.h \
         readWritePPM.h
CFILES = fastiht1.c image_io.c inverse_halftone.c matrix_utils.c readWritePPM.c
OBJFILES = $(CFILES:.c=.o)
BINARIES = fastiht1 fastiht2
SRCS = fastiht2.c $(CFILES)

EXTRA_SRCS = config-gcc.mk config-cc.mk README.txt

include config-$(CC).mk

install:	$(BINARIES)

fastiht1:	$(OBJFILES)
	$(LINKER) $(LINKFLAGS) -o fastiht1 $(OBJFILES)

fastiht2:	fastiht2.o
	$(LINKER) $(LINKFLAGS) -o fastiht2 $< readWritePPM.o

sources:	$(SRCS) $(EXTRA_SRCS)

clean:
	-rm $(OBJFILES) fastiht2.o

realclean:
	-rm $(OBJFILES) fastiht2.o $(BINARIES)

# Generate dependencies using 'gcc -MM'

# Dependencies for both the fastiht1 and fastiht2 programs
readWritePPM.o: readWritePPM.c readWritePPM.h readWriteImage.h

# Dependencies for the fastiht1 program generated by gcc -MM
fastiht1.o: fastiht1.c image_io.h matrix_utils.h inverse_halftone.h
image_io.o: image_io.c image_io.h readWriteImage.h readWritePPM.h
inverse_halftone.o: inverse_halftone.c matrix_utils.h inverse_halftone.h
matrix_utils.o: matrix_utils.c matrix_utils.h

# Dependencies for the fastiht2 program generated
fastiht2.o: fastiht2.c readWriteImage.h readWritePPM.h
